<?php

######################################################
# Website Title
######################################################
$title="Monster WoW Server Cataclysm 4.3.4";

######################################################
# Domain url
#  - With http:// and without trailling slash "/" at end
######################################################
$domain_url="http://monster-wow.net";

######################################################
# Server Address
#  - Used for online/offline status
#  - PHP fsockopen() must be enabled on your web server
######################################################
$server = "84.252.18.47";

######################################################
# SQL Connection
######################################################
$db_user = "ragezone";
$db_pass = "treibal21234566" ;
$db_host = "localhost";

######################################################
# Website Database Name
#  - For this CMS
######################################################
$db_name = "ragezone_auth";

######################################################
# World Database Name
#  - Not so important, helps admin to search item IDs.
######################################################
$item_db ="world";

######################################################
# Accounts Database Name
#  - Where all accounts are stored
######################################################
$acc_db ="ragezone_auth";

######################################################
# Realm Configuration
#  - You can have unlimited amount of realms
#  - Example: (X represents number 1 -> infinity)
#
#  //Server no.X
#  $realm[X] = array(
#  "name" => "Realm Name",
#  "port" => "3306",
#  "port_ra" => "3443",
#  "db"   => "realm_database"
#  );
######################################################
//Realm no.1
$realm[1] = array(
"name" => "LORDAERON 3.3.5a",
"port" => "8085",
"port_ra" => "3443",
"db" => "ragezone_characters"
);
######################################################
# Core Settings (ascent,mangos,trinity or trinity_ra)
######################################################
$server_core ="trinity_ra";

######################################################
# SMTP Settings
######################################################
$smtp_h = "";
$smtp_u = "";
$smtp_p = "";

######################################################
# Vote Settings
#  - You can have unlimited amount of vote urls
#  - Images for vote are stored in:
#  - htdocs/styles/<yourstyle>/images/<votenumber>.jpg
#  Example with 3 vote url's:
#
#  $voteurls = array(
#  1 => "http://vote_url_1",
#  2 => "http://vote_url_2",
#  3 => "http://vote_url_3"
#  );"
######################################################
$voteurls = array(
1 => "http://www.xtremetop100.com/in.php?site=1132309468",
2 => "http://www.jagtoplist.com/in.php?site=15474",
3 => "http://www.gamesitestop100.com/in.php?site=17812",
4 => "http://www.gtop100.com/in.php?site=55495",
5 => "http://www.gamesites200.com/wowprivate/in.php?id=9104",
6 => "http://www.mmorpgtop200.com/in.php?site=7838",
7 => "http://www.mmorpgtoplist.com/in.php?site=34504",
8 => "http://www.inventgamingtop100.com?in=17",
9 => "http://topg.org/in-348033",
10 => "http://wow.top100arena.com/in.asp?id=54187",
);

######################################################
# Style
#  - Located in: htdocs/styles/<style>/
######################################################
$style='default';

######################################################
# Use ToS (1 or 0)
######################################################
$usetos = 0;

######################################################
# Other
######################################################
$module_teleporter_gold="0";


/***************************
***   DONT EDIT BELOW    ***
***************************/
$se_c = "baf9abece3482c2236e47291d35ac07e";
$db_type = "mysql";
$db_prefix = "a_";
$p_connect = false;

$cookie_name = "webwowcms_cookie";
$cookie_domain = "";
$cookie_path = "/";
$cookie_secure = 0;

//autogenerated MaNGOS,Trinity RA
$ra_user="yexs";//admin account
$ra_pass="1234566";//admin password


define('AXE', 1);
?>