<?php

######################################################
# Website Title
######################################################
$title="Vmangos - Free Private Server Vanilla";

######################################################
# Domain url
#  - With http:// and without trailling slash "/" at end
######################################################
$domain_url="https://127.0.0.1";

######################################################
# Server Address
#  - Used for online/offline status
#  - PHP fsockopen() must be enabled on your web server
######################################################
$server = "127.0.0.1";

######################################################
# SQL Connection
######################################################
$db_user = "root";
$db_pass = "ascent" ;
$db_host = "127.0.0.1";

######################################################
# VoteShop Website Connection
######################################################

mysql_connect("$db_host","$db_user", "$db_pass");

######################################################
# Uptime Table
######################################################

$uptime = "realmd";

######################################################
# Arena Teams - Top 5 kills Table
######################################################

$arena_top = "vanillachar";

######################################################
# Player Online Table
######################################################

$player_online = "vanillachar";

######################################################
# Website Database Name
#  - For this CMS
######################################################

$db_name = "realmd";

######################################################
# World Database Name
#  - Not so important, helps admin to search item IDs.
######################################################

$item_db ="mangos";

######################################################
# Accounts Database Name
#  - Where all accounts are stored
######################################################

$acc_db ="realmd";

######################################################
# Realm Configuration
#  - You can have unlimited amount of realms
#  - Example: (X represents number 1 -> infinity)
#
#  //Server no.X
#  $realm[X] = array(
#  "name" => "Realm Name",
#  "port" => "3306",
#  "port_ra" => "3443",
#  "db"   => "realm_database"
#  );
######################################################
//Realm no.1
$realm[1] = array(
"name" => "realm 15x",
"port" => "8085",
"port_ra" => "3443",
"db" => "vanillachar"
);
######################################################
# Core Settings (ascent,mangos,trinity or trinity_ra)
######################################################
$server_core ="trinity_ra";

######################################################
# SMTP Settings
######################################################
$smtp_h = "";
$smtp_u = "";
$smtp_p = "";


$config_Expansions['allowed']['expansion_normal'] = true;
$config_Expansions['allowed']['expansion_tbc'] = true;
$config_Expansions['allowed']['expansion_wotlk'] = false;
$config_Expansions['allowed']['expansion_cata'] = false;




######################################################
# Vote Settings
#  - You can have unlimited amount of vote urls
#  - Images for vote are stored in:
#  - htdocs/styles/<yourstyle>/images/<votenumber>.jpg
#  Example with 3 vote url's:
#
#  $voteurls = array(
#  1 => "http://vote_url_1",
#  2 => "http://vote_url_2",
#  3 => "http://vote_url_3"
#  );"
######################################################
$voteurls = array(
1 => "http://www.xtremetop100.com/in.php?site=1132332464",
2 => "http://www.openwow.com/vote=3186",
3 => "http://www.top100arena.com/in.asp?id=84274",
);

######################################################
# Style
#  - Located in: htdocs/styles/<style>/
######################################################
$style='default';

######################################################
# Use ToS (1 or 0)
######################################################
$usetos = 0;

######################################################
# Other
######################################################
$module_teleporter_gold="0";


/***************************
***   DONT EDIT BELOW    ***
***************************/
$se_c = "baf9abece3482c2236e47291d35ac07e";
$db_type = "mysql";
$db_prefix = "a_";
$p_connect = false;

$cookie_name = "webwowcms_cookie";
$cookie_domain = "";
$cookie_path = "/";
$cookie_secure = 0;

//autogenerated MaNGOS,Trinity RA
$ra_user="admin";//admin account
$ra_pass="admin";//admin password

define('AXE', 1);
?>